apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: defaultallowprivileged-deployment
  namespace: gatekeeper-system
  labels:
{{- range $key, $value := .Values.Labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  match:
    scope: Namespaced
    namespaces:
      - blackbird-services
    labelSelector:
      matchExpressions:
        - key: blackbird.getambassador.io/instance-type
          operator: In
          values:
            - deployment
  applyTo:
    - groups: ["apps"]
      kinds: ["Deployment"]
      versions: ["v1"]
  location: "spec.template.spec.containers[name:*].securityContext.privileged"
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: defaultallowprivileged
  namespace: gatekeeper-system
  labels:
{{- range $key, $value := .Values.Labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  match:
    scope: Namespaced
    namespaces:
      - blackbird-services
    labelSelector:
      matchExpressions:
        - key: blackbird.getambassador.io/instance-type
          operator: In
          values:
            - deployment
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  location: "spec.containers[name:*].securityContext.privileged"
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: defaultallowprivileged-init
  namespace: gatekeeper-system
  labels:
{{- range $key, $value := .Values.Labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  match:
    scope: Namespaced
    namespaces:
      - blackbird-services
    labelSelector:
      matchExpressions:
        - key: blackbird.getambassador.io/instance-type
          operator: In
          values:
            - deployment
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  location: "spec.initContainers[name:*].securityContext.privileged"
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: defaultallowprivileged-ephemeral
  namespace: gatekeeper-system
  labels:
{{- range $key, $value := .Values.Labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  match:
    scope: Namespaced
    namespaces:
      - blackbird-services
    labelSelector:
      matchExpressions:
        - key: blackbird.getambassador.io/instance-type
          operator: In
          values:
            - deployment
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  location: "spec.ephemeralContainers[name:*].securityContext.privileged"
  parameters:
    assign:
      value: false
