apiVersion: v1
kind: Service
metadata:
  annotations:
    kubeception.ingress.type: sni
    kubeception.ingress.wild-http.name: default
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    blackbird.getambassador.io/name: default
    blackbird.getambassador.io/namespace: {{ .Values.AmbassadorNamespace }}
    gateway.envoyproxy.io/owning-gateway-name: aes-gateway
    gateway.envoyproxy.io/owning-gateway-namespace: {{ .Values.AmbassadorNamespace }}
{{- range $key, $value := .Values.Labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
  name: default
  namespace: {{ .Values.AmbassadorNamespace }}
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: wild-http
    port: 80
    protocol: TCP
    targetPort: 10080
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: aes-gateway
    gateway.envoyproxy.io/owning-gateway-namespace: {{ .Values.AmbassadorNamespace }}
  sessionAffinity: None
  type: LoadBalancer
