{{- if .Values.enableClusterPolicies }}
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: seccompprofile-deployment
  namespace: gatekeeper-system
spec:
  match:
    scope: Namespaced
    namespaces:
      - blackbird-services
    labelSelector:
      matchExpressions:
        - key: blackbird.getambassador.io/instance-type
          operator: In
          values:
            - deployment
  applyTo:
    - groups: ["apps"]
      kinds: ["Deployment"]
      versions: ["v1"]
  location: "spec.template.spec.securityContext.seccompProfile.type"
  parameters:
    assign:
      value: RuntimeDefault
{{- end }}
---
{{- if .Values.enableClusterPolicies }}
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: seccompprofile-pod
  namespace: gatekeeper-system
spec:
  match:
    scope: Namespaced
    namespaces:
      - blackbird-services
    labelSelector:
      matchExpressions:
        - key: blackbird.getambassador.io/instance-type
          operator: In
          values:
            - deployment
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  location: "spec.securityContext.seccompProfile.type"
  parameters:
    assign:
      value: RuntimeDefault
{{- end }}